services:
  copilot_proxy:
    container_name: copilot_proxy
    build: .
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    ports:
      - 8080:8080
    restart: unless-stopped
